include: package:lint/strict.yaml

analyzer:
  exclude:
    - build/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
#  language:
#    strict-casts: true
#    strict-raw-types: true
#    strict-inference: true

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: true
    always_use_package_imports: true
    empty_statements: true
    always_declare_return_types: true
    camel_case_extensions: true
    require_trailing_commas: true
