name: mno_opds
description: Contains OPDS1 and OPDS2 parsers using OPDS classes provided by mno_shared.
version: 0.1.1
homepage: https://github.com/Mantano/mno_opds_dart
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dartx: ^1.1.0
  dfunc: ^0.9.0
  fimber: ^0.6.6
  http: ^0.13.6
  universal_io: ^2.2.1
  xml: ^6.3.0
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
