// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_ebook_app/test/view_models/home_provider/getRecent.welltested_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:flutter_ebook_app/models/category.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [CategoryFeed].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryFeed extends _i1.Mock implements _i2.CategoryFeed {
  MockCategoryFeed() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set version(String? _version) => super.noSuchMethod(
        Invocation.setter(
          #version,
          _version,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set encoding(String? _encoding) => super.noSuchMethod(
        Invocation.setter(
          #encoding,
          _encoding,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set feed(_i2.Feed? _feed) => super.noSuchMethod(
        Invocation.setter(
          #feed,
          _feed,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}
