include: package:lints/recommended.yaml
linter:
  rules:
    omit_local_variable_types: false
    public_member_api_docs: false
    unnecessary_this: false
    prefer_single_quotes: false
    prefer_double_quotes: false
    annotate_overrides: true
    prefer_expression_function_bodies: true
    always_declare_return_types: true
    avoid_returning_null_for_future: true
    always_use_package_imports: true
    use_super_parameters: true
