name: mno_streamer
version: 0.1.1
description: Streamer API and multiple file parsers (PDF, CBZ, Epub) for Dart.
homepage: https://github.com/Mantano/mno_streamer_dart
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dartx: ^1.1.0
  dfunc: ^0.9.0
  fimber: ^0.6.6
  image: ^4.0.17
  universal_io: ^2.2.1
  xml: ^6.3.0
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared
  path: ^1.8.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
