name: mno_navigator
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/iridium
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.2
  dartx: ^1.1.0
  dfunc: ^0.9.0
  equatable: ^2.0.5
  fimber: ^0.6.6
  flutter_bloc: ^8.1.3
  flutter_inappwebview: ^5.7.2+3
  flutter_spinkit: ^5.2.0
  photo_view: ^0.14.0
  preload_page_view: ^0.2.0
  rxdart: ^0.27.7
  universal_io: ^2.2.1

  mno_commons:
    path: ../commons
  mno_server:
    path: ../server
  mno_shared:
    path: ../shared
  mno_streamer:
    path: ../streamer
  mno_webview:
    path: ../webview

dev_dependencies:
  test: ^1.24.3
  lints: ^2.1.0

flutter:
  assets:
    - assets/readium/assets/
    - assets/readium/divina/
    - assets/readium/fonts/
    - assets/readium/readium-css/
    - assets/readium/readium-css/cjk-horizontal/
    - assets/readium/readium-css/cjk-vertical/
    - assets/readium/readium-css/fonts/
    - assets/readium/readium-css/rtl/
    - assets/readium/scripts/
    - assets/xpub-shared-js/
    - assets/xpub-js/
    - assets/xpub-js/controllers/
    - assets/xpub-js/model/
    - assets/xpub-js/utils/
