name: mno_lcp
description: This package provides a DART LCP layer (native libraries not provided).
version: 0.1.0
homepage: https://github.com/Mantano/mno_lcp_dart
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  dartx: ^1.1.0
  device_info_plus: ^9.0.1
  ffi: ^2.0.2
  fimber: ^0.6.6
  flutter_archive: ^5.0.0
  mno_fsm: ^0.2.3
  multiple_localization: ^0.3.0
  path: ^1.8.3
  path_provider: ^2.0.15
  shared_preferences: ^2.1.1
  sqflite: ^2.2.8+4
  universal_io:
  url_launcher: ^6.1.11
  uuid: ^3.0.7
  mno_commons:
    path: ../commons
  mno_shared:
    path: ../shared

dependency_overrides:
  intl: ^0.18.1
  collection: ^1.17.2

dev_dependencies:
  test: ^1.24.3
  lints: ^2.1.0

assets:
  - assets/
