// Mocks generated by Mockito 5.4.0 from annotations
// in flutter_ebook_app/test/view_models/genre_provider/getFeed.welltested_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:flutter_ebook_app/models/category.dart' as _i3;
import 'package:flutter_ebook_app/util/api.dart' as _i4;
import 'package:flutter_ebook_app/util/flutter_toast.dart' as _i6;
import 'package:fluttertoast/fluttertoast.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeCategoryFeed_1 extends _i1.SmartFake implements _i3.CategoryFeed {
  _FakeCategoryFeed_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CategoryFeed].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryFeed extends _i1.Mock implements _i3.CategoryFeed {
  MockCategoryFeed() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set version(String? _version) => super.noSuchMethod(
        Invocation.setter(
          #version,
          _version,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set encoding(String? _encoding) => super.noSuchMethod(
        Invocation.setter(
          #encoding,
          _encoding,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set feed(_i3.Feed? _feed) => super.noSuchMethod(
        Invocation.setter(
          #feed,
          _feed,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [Api].
///
/// See the documentation for Mockito's code generation for more information.
class MockApi extends _i1.Mock implements _i4.Api {
  MockApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Dio get dio => (super.noSuchMethod(
        Invocation.getter(#dio),
        returnValue: _FakeDio_0(
          this,
          Invocation.getter(#dio),
        ),
      ) as _i2.Dio);
  @override
  set dio(_i2.Dio? _dio) => super.noSuchMethod(
        Invocation.setter(
          #dio,
          _dio,
        ),
        returnValueForMissingStub: null,
      );
  @override
  _i5.Future<_i3.CategoryFeed> getCategory(String? url) => (super.noSuchMethod(
        Invocation.method(
          #getCategory,
          [url],
        ),
        returnValue: _i5.Future<_i3.CategoryFeed>.value(_FakeCategoryFeed_1(
          this,
          Invocation.method(
            #getCategory,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.CategoryFeed>);
}

/// A class which mocks [Feed].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeed extends _i1.Mock implements _i3.Feed {
  MockFeed() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set xmlLang(String? _xmlLang) => super.noSuchMethod(
        Invocation.setter(
          #xmlLang,
          _xmlLang,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlns(String? _xmlns) => super.noSuchMethod(
        Invocation.setter(
          #xmlns,
          _xmlns,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsDcterms(String? _xmlnsDcterms) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsDcterms,
          _xmlnsDcterms,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsThr(String? _xmlnsThr) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsThr,
          _xmlnsThr,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsApp(String? _xmlnsApp) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsApp,
          _xmlnsApp,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsOpensearch(String? _xmlnsOpensearch) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsOpensearch,
          _xmlnsOpensearch,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsOpds(String? _xmlnsOpds) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsOpds,
          _xmlnsOpds,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsXsi(String? _xmlnsXsi) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsXsi,
          _xmlnsXsi,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsOdl(String? _xmlnsOdl) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsOdl,
          _xmlnsOdl,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set xmlnsSchema(String? _xmlnsSchema) => super.noSuchMethod(
        Invocation.setter(
          #xmlnsSchema,
          _xmlnsSchema,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set id(_i3.Id? _id) => super.noSuchMethod(
        Invocation.setter(
          #id,
          _id,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set title(_i3.Id? _title) => super.noSuchMethod(
        Invocation.setter(
          #title,
          _title,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set updated(_i3.Id? _updated) => super.noSuchMethod(
        Invocation.setter(
          #updated,
          _updated,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set icon(_i3.Id? _icon) => super.noSuchMethod(
        Invocation.setter(
          #icon,
          _icon,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set author(_i3.Author? _author) => super.noSuchMethod(
        Invocation.setter(
          #author,
          _author,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set link(List<_i3.Link>? _link) => super.noSuchMethod(
        Invocation.setter(
          #link,
          _link,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set opensearchTotalResults(_i3.Id? _opensearchTotalResults) =>
      super.noSuchMethod(
        Invocation.setter(
          #opensearchTotalResults,
          _opensearchTotalResults,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set opensearchItemsPerPage(_i3.Id? _opensearchItemsPerPage) =>
      super.noSuchMethod(
        Invocation.setter(
          #opensearchItemsPerPage,
          _opensearchItemsPerPage,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set opensearchStartIndex(_i3.Id? _opensearchStartIndex) => super.noSuchMethod(
        Invocation.setter(
          #opensearchStartIndex,
          _opensearchStartIndex,
        ),
        returnValueForMissingStub: null,
      );
  @override
  set entry(List<_i3.Entry>? _entry) => super.noSuchMethod(
        Invocation.setter(
          #entry,
          _entry,
        ),
        returnValueForMissingStub: null,
      );
  @override
  Map<String, dynamic> toJson() => (super.noSuchMethod(
        Invocation.method(
          #toJson,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);
}

/// A class which mocks [FlutterToastWrapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterToastWrapper extends _i1.Mock
    implements _i6.FlutterToastWrapper {
  MockFlutterToastWrapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool?> showToast({
    required String? msg,
    _i7.Toast? toastLength,
    int? timeInSecForIosWeb,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #showToast,
          [],
          {
            #msg: msg,
            #toastLength: toastLength,
            #timeInSecForIosWeb: timeInSecForIosWeb,
          },
        ),
        returnValue: _i5.Future<bool?>.value(),
      ) as _i5.Future<bool?>);
}
